name: quote_generator

on:
  workflow_dispatch:
  schedule:
  - cron: "00 00 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 12.21.0
    - run: npm ci
    - name: Generate quote
      run: npm run generate
    - name: Update README.md
      run: |
        git config --global user.email "minhphucpk.1997@gmail.com"
        git config --global user.name "dinhphuc"
        git add .
        git commit -m "Updated README.md" || echo "Random Quote to commit"
        git push
